fix for 'Connection broken: IncompleteRead(0 bytes read)'?
While the docker builds are locally working without any
problem, they consistently fail on docker hub. There, I
get the following error:

Installing pandoc via cabal.
Resolving dependencies...
Build profile: -w ghc-8.8.3 -O1
In order, the following will be built (use -v for more details):
- pandoc-2.10.1 (lib) (requires download & build)
- pandoc-2.10.1 (exe:pandoc) (requires download & build)
Downloading pandoc-2.10.1
Downloaded pandoc-2.10.1
Starting pandoc-2.10.1 (lib)
Building pandoc-2.10.1 (lib)
Unexpected error
Encountered error: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))
Traceback (most recent call last):
File "/stage/builder/runner.py", line 297, in _run
self.build()
File "/stage/builder/runner.py", line 221, in build
self._build()
File "/stage/builder/runner.py", line 209, in _build
cache_repo)
File "/stage/builder/build.py", line 43, in build_image
for line in stream:
File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 290, in _stream_helper
for chunk in json_stream(self._stream_helper(response, False)):
File "/usr/local/lib/python2.7/dist-packages/docker/utils/json_stream.py", line 66, in split_buffer
for data in stream_as_text(stream):
File "/usr/local/lib/python2.7/dist-packages/docker/utils/json_stream.py", line 22, in stream_as_text
for data in stream:
File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py", line 296, in _stream_helper
data = reader.read(1)
File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 311, in read
flush_decoder = True
File "/usr/lib/python2.7/contextlib.py", line 35, in __exit__
self.gen.throw(type, value, traceback)
File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/response.py", line 244, in _error_catcher
raise ProtocolError('Connection broken: %r' % e, e)
ProtocolError: ('Connection broken: IncompleteRead(0 bytes read)', IncompleteRead(0 bytes read))

I am at a total loss what that means.
I somehow believe that this error is not thrown in the
Dockerfile itsel, because I think that it won't use python
to build pandoc, a Haskell project.
Also the
'File "/usr/local/lib/python2.7/dist-packages/docker/api/client.py"'
kind of looks as if this error appears in the docker hub code
invoking the build.
The only possible reason I could imagine is that this could be
some sort of connection time out.
Maybe the building of pandoc itself does not write to the stdout
for long enough to make the connection of the build environment
to the build process time out.

In the hope to fix this, I will set all cabal install scripts
to maximum verbosity.
Hopefully, this will write output all the time and feed enough
data through the connection to prevent it from timing out.

Of course, this could also be nonesense.
But it is the best shot I got right now....